let content,users,logs,lastQuality;
function safeProgress(p){const s=p&&typeof p==='object'?p:{};return Object.assign({},s,{history:Array.isArray(s.history)?s.history.filter(h=>h&&Number.isFinite(h.score)):[]})}
function notice(s){document.getElementById('notice').textContent=s}
async function openApp(){const c=await api('content');content=c.content;contentRevision=c.revision;bar();document.getElementById('adminContent').hidden=false;await showUsers()}
async function showUsers(){try{const r=await api('admin/users'),i=r.insights||{};users=r.users;logs=r.logs;document.getElementById('panel').innerHTML='<div class="row"><div class="card"><h3>'+i.onboarded+' / '+i.accounts+'</h3><p>已建立学习目标</p></div><div class="card"><h3>'+i.baseline+'</h3><p>已完成基线</p></div><div class="card"><h3>'+i.started+'</h3><p>已开始学习</p></div><div class="card"><h3>'+i.fiftyAnswers+'</h3><p>已完成50题</p></div><div class="card"><h3>'+(i.averageGrowth===null?'—':(i.averageGrowth>=0?'+':'')+i.averageGrowth+'分')+'</h3><p>前后测平均成长</p></div></div><div class="card scroll"><button class="btn primary" onclick="exportScores()">导出成绩清单</button><table><tr><th>账号</th><th>状态</th><th>学习目标</th><th>基线 → 后测</th><th>已学 / 答题</th><th>管理</th></tr>'+users.filter(u=>u.role==='user').map(u=>{const s=safeProgress(u.progress),p=u.profile||{},growth=p.baseline&&p.final?p.final.score-p.baseline.score:null;return '<tr><td>'+u.id+'<br><span class="small">'+esc(u.lastLogin?new Date(u.lastLogin).toLocaleString():'尚未登录')+'</span></td><td>'+(!u.enabled?'停用':u.locked?'锁定':'正常')+'</td><td>'+esc(({foundation:'零基础入门',hr_manager:'企业人资',economist:'中级经济师',labor:'劳动合规',talent:'人才发展'})[p.goal]||'未设置')+'</td><td>'+(p.baseline?p.baseline.score:'—')+' → '+(p.final?p.final.score:'—')+(growth!==null?'<br><b>'+(growth>=0?'+':'')+growth+'分</b>':'')+'</td><td>'+Object.keys(s.doneAtoms||{}).length+' / '+Object.keys(s.answers||{}).length+'</td><td>'+[['toggle',u.enabled?'停用':'启用'],['logout','强制登出'],['reset','重设密码'],['unlock','解锁']].map(([a,t])=>'<button class="btn" onclick="manage(\''+u.id+'\',\''+a+'\')">'+t+'</button>').join('')+'</td></tr>'}).join('')+'</table></div><details class="card"><summary>操作记录</summary>'+logs.map(l=>'<p class="small">'+esc(new Date(l.at).toLocaleString()+' · '+l.actor+' · '+l.action)+'</p>').join('')+'</details>'}catch(e){notice(e.message)}}
async function manage(id,action){if(['reset','toggle','logout'].includes(action)&&!confirm('确认对 '+id+' 执行此操作？学习记录将保留。'))return;try{const r=await api('admin/user','POST',{id,action});await showUsers();notice(r.password?id+' 新临时密码：'+r.password+'（请立即保存并单独交给使用者）':'操作已完成')}catch(e){notice(e.message)}}
const feedbackLabels={new:'已收到',reviewing:'处理中',resolved:'已处理'},feedbackTypes={suggestion:'功能建议',content:'内容建议',experience:'使用体验',problem:'问题回报',other:'其他'};
async function showFeedback(status=''){try{const r=await api('admin/feedback'+(status?'?status='+encodeURIComponent(status):'')),list=r.feedbacks,c=r.counts;document.getElementById('panel').innerHTML='<div class="feedback-toolbar"><button class="btn '+(!status?'primary':'')+'" onclick="showFeedback()">全部</button><button class="btn '+(status==='new'?'primary':'')+'" onclick="showFeedback(\'new\')">待阅 '+c.new+'</button><button class="btn '+(status==='reviewing'?'primary':'')+'" onclick="showFeedback(\'reviewing\')">处理中 '+c.reviewing+'</button><button class="btn '+(status==='resolved'?'primary':'')+'" onclick="showFeedback(\'resolved\')">已处理 '+c.resolved+'</button><span class="count">共 '+(c.new+c.reviewing+c.resolved)+' 笔</span></div>'+(list.length?list.map(f=>'<article class="card feedback-card '+f.status+'"><div class="row"><div><span class="small">'+esc(feedbackTypes[f.category]||'其他')+' · '+esc(f.userId)+' · '+esc(new Date(f.createdAt).toLocaleString())+'</span><h3>'+esc(f.subject)+'</h3></div><div style="text-align:right"><b>'+esc(feedbackLabels[f.status]||f.status)+'</b></div></div><p class="feedback-text">'+esc(f.message)+'</p><label>回复使用者<textarea id="freply-'+f.id+'" maxlength="1000" placeholder="使用者会在前台看到这段回复">'+esc(f.publicReply||'')+'</textarea></label><label>内部处理备注<textarea id="fnote-'+f.id+'" maxlength="1000" placeholder="仅管理员可见">'+esc(f.adminNote||'')+'</textarea></label><div><button class="btn" onclick="updateFeedback(\''+f.id+'\',\'new\')">标为待阅</button><button class="btn" onclick="updateFeedback(\''+f.id+'\',\'reviewing\')">开始处理</button><button class="btn primary" onclick="updateFeedback(\''+f.id+'\',\'resolved\')">回复并完成</button></div></article>').join(''):'<div class="card"><h3>目前没有反馈</h3><p class="small">符合当前筛选条件的意见会显示在这里。</p></div>')}catch(e){notice(e.message)}}
async function updateFeedback(id,status){try{const note=document.getElementById('fnote-'+id).value,reply=document.getElementById('freply-'+id).value;await api('admin/feedback','POST',{id,status,note,reply});notice('反馈状态与回复已更新');await showFeedback(status==='resolved'?'resolved':'')}catch(e){notice(e.message)}}
function exportScores(){const rows=['账号,已学知识点,答题数,正确题数,模考次数,最高分'];users.filter(u=>u.role==='user').forEach(u=>{const s=safeProgress(u.progress);rows.push([u.id,Object.keys(s.doneAtoms||{}).length,Object.keys(s.answers||{}).length,Object.values(s.answers||{}).filter(Boolean).length,(s.history||[]).length,Math.max(0,...(s.history||[]).map(h=>h.score))].join(','))});downloadFile('学习成绩.csv','\ufeff'+rows.join('\r\n'),'text/csv;charset=utf-8')}
async function publish(){const r=await api('admin/content','PUT',{content,revision:contentRevision});contentRevision=r.revision;notice('已发布，使用者下次检查连接时将收到重新载入提示。')}
function moduleOptions(){return content.modules.map((m,i)=>'<option value="'+i+'">'+esc(m.name)+'</option>').join('')}
async function showQuality(){try{const r=await api('admin/quality'),s=r.summary,q=content.learningCoverage||{};lastQuality=r;document.getElementById('panel').innerHTML='<div class="card release '+(r.ready?'':'fail')+'"><h2>'+(r.ready?'✅ 上线品质检查通过':'⚠️ 暂停发布')+'</h2><p>'+(r.ready?'题库结构、学习卡与来源映射符合当前上线规则。后台每次发布内容时会自动重新检查。':'请先修复下方未通过项目，系统会阻止不合格内容发布。')+'</p><span class="small">检查时间：'+esc(new Date(r.generatedAt).toLocaleString())+'</span><p><button class="btn primary" onclick="exportQuality()">导出检查报告</button></p></div><div class="row"><div class="card"><h3>'+s.questions.toLocaleString()+' 题</h3><p>题干与选项组合唯一</p></div><div class="card"><h3>'+s.guided+' / '+s.atoms+'</h3><p>完整学习卡与来源映射</p></div><div class="card"><h3>'+s.officialReviewed+' 项</h3><p>已按官方原文重点复核</p></div><div class="card"><h3>'+s.customQuestions+' 题</h3><p>独立案例题</p></div></div><div class="card"><h3>自动品质闸门</h3><div class="gate">'+r.checks.map(x=>'<div class="gate-item '+(x.pass?'pass':'fail')+'"><span>'+(x.pass?'✓ ':'✕ ')+esc(x.name)+'</span><b>'+esc(x.detail)+'</b></div>').join('')+'</div></div><div class="card"><h3>内容治理提醒</h3><p>自动检查负责结构、覆盖与一致性，不取代法律或专家审校。政策、税率、缴费基数、最低工资与考试大纲应按地区及发布日期持续复核。</p><p class="small">学习卡版本：'+esc(q.version||'—')+' · 正确答案分布 A/B/C/D：'+s.answerCounts.join(' / ')+'</p></div>'}catch(e){notice(e.message)}}
function exportQuality(){if(lastQuality)downloadFile('HR上线品质检查.json',JSON.stringify(lastQuality,null,2))}
function showKnowledge(){document.getElementById('panel').innerHTML='<div class="card"><h3>编辑知识点</h3><label>模块<select id="module" onchange="chapterOptions()">'+moduleOptions()+'</select></label><label>章节<select id="chapter" onchange="knowledgeOptions()"></select></label><label>知识点<select id="atom" onchange="editAtom()"></select></label><label>名称<input id="atomName"></label><label>核心原则<textarea id="atomRule"></textarea></label><button class="btn primary" onclick="saveAtom()">保存并发布</button></div>';chapterOptions()}
function chapterOptions(){const m=content.modules[+document.getElementById('module').value];document.getElementById('chapter').innerHTML=m.chapters.map((ch,i)=>'<option value="'+i+'">'+esc(ch[0])+'</option>').join('');knowledgeOptions()}
function knowledgeOptions(){const ch=content.modules[+document.getElementById('module').value].chapters[+document.getElementById('chapter').value];document.getElementById('atom').innerHTML=ch[1].map((x,i)=>'<option value="'+i+'">'+esc(x.name)+'</option>').join('');editAtom()}
function editAtom(){const raw=content.modules[+document.getElementById('module').value].chapters[+document.getElementById('chapter').value][1][+document.getElementById('atom').value];document.getElementById('atomName').value=raw.name;document.getElementById('atomName').readOnly=false;document.getElementById('atomRule').value=raw.rule}
async function saveAtom(){try{const n=document.getElementById('atomName').value.trim(),r=document.getElementById('atomRule').value.trim();if(!n||!r||n.includes('|')||r.includes('|'))throw Error('请填写名称与原则，不可包含分隔符 |');const old=content.modules[+document.getElementById('module').value].chapters[+document.getElementById('chapter').value][1][+document.getElementById('atom').value],next=Object.assign({},old,{name:n,rule:r});if(n!==old.name||r!==old.rule){delete next.lesson;delete next.reviewedVersion;delete next.guidedVersion}content.modules[+document.getElementById('module').value].chapters[+document.getElementById('chapter').value][1][+document.getElementById('atom').value]=next;await publish();knowledgeOptions()}catch(e){notice(e.message)}}
function showQuestions(){document.getElementById('panel').innerHTML='<div class="card"><h3>独立题目编辑</h3><p class="small">选择知识点和题目序号，可编辑对应题目的题干、选项、答案与解析。</p><label>模块<select id="qm" onchange="questionAtoms()">'+moduleOptions()+'</select></label><label>知识点<select id="qa" onchange="loadQuestion()"></select></label><label>题目序号<select id="qv" onchange="loadQuestion()">'+Array.from({length:10},(_,i)=>'<option value="'+i+'">第'+(i+1)+'题</option>').join('')+'</select></label><label>题干<textarea id="qstem"></textarea></label>'+[0,1,2,3].map(i=>'<label>选项 '+String.fromCharCode(65+i)+'<textarea id="qo'+i+'"></textarea></label>').join('')+'<label>正确答案<select id="qanswer">'+[0,1,2,3].map(i=>'<option value="'+i+'">'+String.fromCharCode(65+i)+'</option>').join('')+'</select></label><label>解析<textarea id="qexplanation"></textarea></label><button class="btn primary" onclick="saveQuestion()">保存并发布</button></div>';questionAtoms()}
function questionAtoms(){const m=content.modules[+document.getElementById('qm').value];document.getElementById('qa').innerHTML=m.chapters.flatMap((ch,ci)=>ch[1].map((a,ai)=>'<option value="'+ci+','+ai+'">'+esc(ch[0]+' / '+a.name)+'</option>')).join('');loadQuestion()}
function selectedQuestion(){const mi=+document.getElementById('qm').value,m=content.modules[mi],[ci,ai]=document.getElementById('qa').value.split(',').map(Number),v=+document.getElementById('qv').value,raw=m.chapters[ci][1][ai];return {mi,m,ci,ai,v,raw,id:raw.id+'-V'+(v+1)}}
async function loadQuestion(){const x=selectedQuestion();try{const q=await api('admin/question?id='+encodeURIComponent(x.id));if(selectedQuestion().id!==x.id)return;document.getElementById('qstem').value=q.stem;for(let i=0;i<4;i++)document.getElementById('qo'+i).value=q.options[i];document.getElementById('qanswer').value=q.answer;document.getElementById('qexplanation').value=q.explanation}catch(e){notice('题目读取失败：'+e.message)}}
async function saveQuestion(){try{const x=selectedQuestion(),q={stem:document.getElementById('qstem').value,options:[0,1,2,3].map(i=>document.getElementById('qo'+i).value),answer:+document.getElementById('qanswer').value,explanation:document.getElementById('qexplanation').value};if(!q.stem||q.options.some(o=>!o)||!q.explanation)throw Error('请完整填写题目');content.overrides=content.overrides||{};content.overrides[x.id]=q;await publish()}catch(e){notice(e.message)}}
function showSettings(){document.getElementById('panel').innerHTML='<div class="card"><h3>前台内容与设置</h3><label>系统名称<input id="title" value="'+esc(content.title||'中国人力资源职能系统')+'"></label><button class="btn primary" onclick="saveTitle()">保存名称</button><details><summary>完整内容编辑（模块、章节顺序、官方资料与题目模板）</summary><p class="note">知识点已有固定ID，可调整名称和顺序。请保持已有ID不变；删除需另行归档迁移。发布前系统会检查ID完整性。</p><textarea id="fullContent" style="min-height:460px">'+esc(JSON.stringify(content,null,2))+'</textarea><button class="btn primary" onclick="saveFull()">验证并发布完整内容</button></details></div>'}
async function saveTitle(){try{content.title=document.getElementById('title').value;await publish()}catch(e){notice(e.message)}}
async function saveFull(){try{const next=JSON.parse(document.getElementById('fullContent').value);if(!confirm('发布完整内容？当前内容会自动备份。'))return;const previous=content;content=next;try{await publish()}catch(e){content=previous;throw e}}catch(e){notice(e.message)}}
async function backup(){try{downloadFile('HR内容与学习数据备份.json',JSON.stringify(await api('admin/backup'),null,2));notice('备份已导出，不含账号密码。')}catch(e){notice(e.message)}}
boot();

