const ENTRY=/\/admin(?:\.html)?\/?$/i.test(location.pathname)?'admin':'user';
const API_BASE='https://esg-api-six.vercel.app/api/hr?path=';
const TOKENKEY='hr_online_'+ENTRY;let token=sessionStorage.getItem(TOKENKEY)||'',me=null,contentRevision=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,method='GET',data){const r=await fetch(API_BASE+encodeURIComponent(path),{method,headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:data===undefined?undefined:JSON.stringify(data),cache:'no-store'});const v=await r.json();if(!r.ok){if(r.status===401&&path!=='login')expire(v.error);throw Error(v.error)}return v}
function expire(msg){token='';me=null;sessionStorage.removeItem(TOKENKEY);document.querySelectorAll('.online-content').forEach(x=>x.hidden=true);document.getElementById('onlineBar').hidden=true;if(window.hrBridge)window.hrBridge.stop();login(msg)}
function login(message=''){const gate=document.getElementById('onlineGate'),admin=ENTRY==='admin';gate.hidden=false;gate.innerHTML='<div class="login-shell '+(admin?'admin-login':'user-login')+'"><section class="login-story"><div class="login-story-inner"><div class="login-mark">HR</div><div class="login-kicker">HUMAN RESOURCE LEARNING SYSTEM</div><h1>'+(admin?'HR系统管理中心':'中国人力资源职能系统')+'</h1><p>'+(admin?'统一管理账号、学习数据、内容质量与使用者反馈。':'以目标路径、知识学习与阶段测验，逐步建立专业的人力资源职能。')+'</p><div class="login-points"><span>知识学习</span><span>刷题训练</span><span>能力诊断</span><span>错题回补</span></div></div></section><section class="login-panel"><div class="login-card"><div class="login-card-mark">'+(admin?'管理':'HR')+'</div><h2>'+(admin?'后台管理员登录':'登入系统')+'</h2><p>'+(admin?'仅限授权管理员使用':'请使用已分配的学习账号')+'</p><form id="login"><label>账号<input name="id" autocomplete="username" required placeholder="请输入账号" autofocus></label><label>密码<input name="password" type="password" autocomplete="current-password" required placeholder="请输入密码"></label><p role="alert" id="loginError">'+esc(message)+'</p><button class="btn primary">'+(admin?'进入管理后台':'登入')+'</button></form>'+(admin?'':'<a class="trial-entry" href="../trial/">无需账号，先体验试用版</a>')+'<div class="login-links">'+(admin?'<a href="./">← 返回使用者登录</a>':'<a href="admin.html">⚙ 管理后台</a>')+'</div></div></section></div>';document.getElementById('login').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const f=new FormData(e.target),r=await api('login','POST',{id:f.get('id'),password:f.get('password'),entry:ENTRY});token=r.token;sessionStorage.setItem(TOKENKEY,token);me=r.user;await openApp()}catch(err){document.getElementById('loginError').textContent=err.message;b.disabled=false}}}
function passwordForm(required=false){document.querySelectorAll('.online-content').forEach(x=>x.hidden=true);const gate=document.getElementById('onlineGate');gate.hidden=false;gate.innerHTML='<div class="card"><h2>'+'修改密码'+'</h2><form id="changePassword"><label>当前密码<input name="old" type="password" autocomplete="current-password" required></label><label>新密码（至少10位，含字母和数字）<input name="password" type="password" autocomplete="new-password" minlength="10" required></label><label>确认密码<input name="confirm" type="password" autocomplete="new-password" required></label><p id="passwordError" role="alert"></p><button class="btn primary">保存</button><button type="button" class="btn" onclick="logout()">退出</button></form></div>';document.getElementById('changePassword').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);if(f.get('password')!==f.get('confirm'))throw Error('两次密码不一致');await api('password','POST',{old:f.get('old'),password:f.get('password')});me.mustChange=false;await openApp()}catch(err){document.getElementById('passwordError').textContent=err.message}}}
async function logout(){try{if(window.flushProgress)await window.flushProgress();if(window.flushLearning)await window.flushLearning()}catch(e){alert('学习记录尚未保存，请检查连接后重试退出。');return}try{await api('logout','POST',{})}catch{}expire('已退出')}
function bar(){document.getElementById('onlineGate').hidden=true;const b=document.getElementById('onlineBar');b.hidden=false;b.innerHTML='<span id="syncStatus"></span> <b>👤 '+esc(me.id)+'</b> <button class="btn" onclick="passwordForm()">修改密码</button> <button class="btn" onclick="logout()">退出</button>'}
async function boot(){if(!token)return login();try{me=(await api('session')).user;if(me.role!==ENTRY){expire('请从对应入口登录');return}await openApp()}catch(e){login(e.message)}}
setInterval(async()=>{if(!token)return;try{const r=await api('session');if(contentRevision&&r.revision!==contentRevision&&ENTRY==='user'){document.getElementById('syncStatus').innerHTML='课程已更新 <button class="btn" onclick="location.reload()">重新载入</button>';if(window.hrBridge)window.hrBridge.stop();document.querySelector('.app').hidden=true}}catch(e){if(token)document.getElementById('syncStatus').textContent='连接中断，请检查网络'}},4000);
function downloadFile(name,value,type='application/json'){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([value],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}

